set nocompatible
" new add here
set cryptmethod=blowfish2

set incsearch
set showmatch
set smartcase
set ignorecase

set number
set linebreak
set scrolloff=2

set hlsearch
"set background=dark

set hidden
set showcmd
set ruler

set nrformats-=octal
set backspace=indent,eol,start

set autoindent
set smartindent
set expandtab
set shiftwidth=4
set softtabstop=4
set tabstop=4
set shiftround

set foldmethod=marker
set foldmarker={{{,}}}

set timeout
set timeoutlen=1000
set ttimeoutlen=100

set backup
if &backupdir =~# '^\.,'
	let &backupdir = "/Users/pengjun/Library/Vim/backup," . &backupdir
endif

set swapfile
if &directory =~# '^\.,'
    let &directory = "/Users/pengjun/Library/Vim/swap," . &directory
endif

set wildmenu
set wildmode=full
set undofile
if &undodir =~# '^\.\%(,\|$\)'
    let &undodir = "/Users/pengjun/Library/Vim/undo," . &undodir
endif

"set gdefault

colorscheme peachpuff
filetype plugin indent on
syntax on

"let mapleader=","

autocmd BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$") | exec "normal g'\"" | endif

augroup vimscript
    autocmd!
    autocmd BufWritePost $MYVIMRC source $MYVIMRC
augroup END

" IDE
let Tlist_Show_One_File = 1
let Tlist_Use_Right_Window = 1

" C, java
autocmd FileType c set foldmethod=syntax
autocmd FileType java set foldmethod=syntax

" Python 
autocmd FileType python set foldmethod=indent

" javascript
function! JavaScriptFold()
    setl foldmethod=syntax
    setl foldlevelstart=1
    syn region foldBraces start=/{/ end=/}/ transparent fold keepend extend

    function! FoldText()
        return substitute(getline(v:foldstart), '{.*', '{...}', '')
    endfunction
    setl foldtext=FoldText()
endfunction
autocmd FileType javascript call JavaScriptFold()

" All fold is open
set foldlevelstart=10
